-- AlterTable
ALTER TABLE "User" ADD COLUMN     "advanceAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "applicantSignature" TEXT,
ADD COLUMN     "educationDegree" TEXT,
ADD COLUMN     "educationInstitution" TEXT,
ADD COLUMN     "educationYearCompleted" TEXT,
ADD COLUMN     "epfoEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "epfoNumber" TEXT,
ADD COLUMN     "esicEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "esicNumber" TEXT,
ADD COLUMN     "loanAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "positionAppliedFor" TEXT,
ADD COLUMN     "previousCompany" TEXT,
ADD COLUMN     "previousEmploymentDates" TEXT,
ADD COLUMN     "previousPosition" TEXT,
ADD COLUMN     "referenceName" TEXT,
ADD COLUMN     "referencePhone" TEXT,
ADD COLUMN     "referenceRelationship" TEXT,
ADD COLUMN     "skillsQualifications" TEXT,
ADD COLUMN     "tdsEnabled" BOOLEAN NOT NULL DEFAULT false;
